export const PATCH_CACHE_DURATION = 300
export const PATCH_INTRODUCTION_CACHE_DURATION = 300
export const PATCH_FAVORITE_CACHE_DURATION = 60
export const HOME_CACHE_DURATION = 60
export const GALGAME_LIST_CACHE_DURATION = 60
export const RESOURCE_LIST_CACHE_DURATION = 60
export const PATCH_RESOURCE_DETAIL_CACHE_DURATION = 60
export const USER_PENDING_RESOURCE_CACHE_DURATION = 60
export const TAG_LIST_CACHE_DURATION = 300
export const COMPANY_LIST_CACHE_DURATION = 300
// 关键词搜索的精确 totalHits：与页码无关，翻页/热词重复查询共享，短 TTL 兜住索引更新
export const SEARCH_TOTAL_HITS_CACHE_DURATION = 60
export const COMMENT_CACHE_DURATION = 60
export const MARKDOWN_HTML_CACHE_DURATION = 5 * 60
export const MARKDOWN_HTML_CACHE_MAX_MARKDOWN_BYTES = 128 * 1024
export const MARKDOWN_HTML_CACHE_MAX_HTML_BYTES = 256 * 1024
